language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.6

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover=build/logs/coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
    fi
