language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
