version: "3"
services:
  site:
    command: bash -c "
      gem install 'jekyll-github-metadata'
      && jekyll serve --config _config.yml,_config_local.yml"
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 8080:4000
